#!/usr/bin/env python3
"""
VRT1 shared conformance vectors — round 2.

Supersedes the negative half of `gen-insight-vectors.py`. Two changes of substance:

  1. Every negative ships as LITERAL canonical bytes plus its expected action_id, and each
     violates EXACTLY ONE rule. A negative that has to be reconstructed by the reader tests
     the reader's construction, not the rule. (See LESSON-negative-vectors-must-be-inputs.md.)

  2. Adds `key_registry_snapshot` as a generic VRT1 record type — not vendor-namespaced,
     because every attester that publishes a key registry has the same problem: the registry
     lives on the operator's own server and its validity windows are self-asserted.
     Type contributed by Insight (oracleinsight.xyz); generalised with their agreement.

Self-contained: hashlib + a pure-python BIP-340 implementation. No third-party libraries, so
any implementation can diff against this file directly.

Outputs
  conformance-vectors/    shared suite (both sides run this)

The generic key_registry_snapshot vectors are NOT written here: they are generated by
vrt1-spec's own tests/generate_vectors.py, under that repo's key and timestamp conventions,
and are covered by its byte-stability test. This script writes the design rationale and the
byte-exact interop vector for Insight's own draft record.

Every artifact is re-verified after generation; the script exits non-zero on any failure.
"""
import json, hashlib, sys, os, calendar, time

# ---------------- secp256k1 / BIP-340 ----------------
P = 2**256 - 2**32 - 977
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8

def _inv(a, m): return pow(a, m - 2, m)

def _add(p1, p2):
    if p1 is None: return p2
    if p2 is None: return p1
    x1, y1 = p1; x2, y2 = p2
    if x1 == x2 and (y1 + y2) % P == 0: return None
    lam = ((3 * x1 * x1) * _inv(2 * y1, P) if p1 == p2
           else (y2 - y1) * _inv(x2 - x1, P)) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)

def _mul(k, pt):
    r = None
    while k:
        if k & 1: r = _add(r, pt)
        pt = _add(pt, pt); k >>= 1
    return r

def sha256(b): return hashlib.sha256(b).digest()
def sha256d(b): return sha256(sha256(b))

def tagged_hash(tag, msg):
    t = sha256(tag.encode())
    return sha256(t + t + msg)

def lift_x(x):
    if x >= P: return None
    y2 = (pow(x, 3, P) + 7) % P
    y = pow(y2, (P + 1) // 4, P)
    if (y * y - y2) % P != 0: return None
    return (x, y if y % 2 == 0 else P - y)

def schnorr_sign(msg, seck, aux):
    d0 = int.from_bytes(seck, 'big')
    assert 1 <= d0 < N
    Pt = _mul(d0, (GX, GY))
    d = d0 if Pt[1] % 2 == 0 else N - d0
    px = Pt[0].to_bytes(32, 'big')
    t = (d ^ int.from_bytes(tagged_hash("BIP0340/aux", aux), 'big')).to_bytes(32, 'big')
    k0 = int.from_bytes(tagged_hash("BIP0340/nonce", t + px + msg), 'big') % N
    assert k0 != 0
    R = _mul(k0, (GX, GY))
    k = k0 if R[1] % 2 == 0 else N - k0
    rx = R[0].to_bytes(32, 'big')
    e = int.from_bytes(tagged_hash("BIP0340/challenge", rx + px + msg), 'big') % N
    return rx + ((k + e * d) % N).to_bytes(32, 'big'), px

def schnorr_verify(msg, pub, sig):
    Pt = lift_x(int.from_bytes(pub, 'big'))
    if Pt is None: return False
    r = int.from_bytes(sig[:32], 'big'); s = int.from_bytes(sig[32:], 'big')
    if r >= P or s >= N: return False
    e = int.from_bytes(tagged_hash("BIP0340/challenge", sig[:32] + pub + msg), 'big') % N
    R = _add(_mul(s, (GX, GY)), _mul(N - e, Pt))
    return R is not None and R[1] % 2 == 0 and R[0] == r

# ---------------- VRT1 primitives ----------------
def canon(o):
    return json.dumps(o, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()

def action_id(payload): return tagged_hash("VRT1/agent-action", canon(payload))

def norm_hex(v):                       # Class A: strip 0x, lowercase
    return (v[2:] if v[:2].lower() == "0x" else v).lower()

DEMO_SECK = bytes.fromhex("5" * 64)    # DEMO ONLY, published deliberately. Never a real key.
AUX = bytes(32)                        # fixed aux_rand, per the reference vector convention
_, DEMO_PX = schnorr_sign(b'\x00' * 32, DEMO_SECK, AUX)
DEMO_AGENT = DEMO_PX.hex()

def sign_action(a):
    aid = action_id(a)
    sig, _ = schnorr_sign(aid, DEMO_SECK, AUX)
    return aid, sig

def vec(a, note=None):
    """A complete positive vector: the payload, its literal bytes, its id, its signature."""
    aid, sig = sign_action(a)
    out = {"action": a,
           "canonical_bytes_hex": canon(a).hex(),
           "canonical_bytes_len": len(canon(a)),
           "action_id_hex": aid.hex(),
           "sig_hex": sig.hex(),
           "agent_pubkey_xonly_hex": a["agent"],
           "verify_result_expected": True}
    if note: out["note"] = note
    return out

def negvec(case, rule, a):
    """A negative vector: literal bytes + expected id. Exactly one rule violated."""
    return {"case": case, "rule_violated": rule,
            "canonical_bytes_hex": canon(a).hex(),
            "canonical_bytes_len": len(canon(a)),
            "action_id_hex": action_id(a).hex(),
            "verify_expected": False}

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "conformance-vectors")
os.makedirs(OUT, exist_ok=True)

def w(path, name, obj):
    with open(os.path.join(path, name), "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False, sort_keys=True); f.write("\n")
    print("  wrote", os.path.relpath(os.path.join(path, name), HERE))

CHECKS = []
def ck(label, cond):
    CHECKS.append((label, bool(cond)))

# =====================================================================================
# PART 1 — insight.oracle-safety-check: the positive (unchanged) and five literal negatives
# =====================================================================================
SRC = os.path.join(HERE, "insight-vectors")
rec = json.load(open(os.path.join(SRC, "source-receipt.json")))["attestation"]
d = rec["data"]
shipped = json.load(open(os.path.join(SRC, "action.json")))
ACTION = shipped["action"]

CANON_ID = "157a3cb81e437eb5c4e57e3756e9237bca2f936c0dd7e72ab6b3995433eba8ac"
ck("round-1 positive still reproduces (157a3cb8…)", action_id(ACTION).hex() == CANON_ID)
ck("round-1 positive is still 1769 bytes", len(canon(ACTION)) == 1769)

HEX_A  = ["reasonCodesHash", "requestHash", "evaluatedAssetIdsHash", "providerObservationsHash"]
UINTS  = ["subjectChainId", "tradeAmountUsd", "consensusPrice", "maxDeviationBps",
          "manipulationRiskBps", "participantCount", "requiredParticipantCount",
          "sourceGroupCount", "crossProviderAgreementBps", "maxStablecoinDepegBps",
          "maxDataAgeSeconds", "recommendedMaxPositionUsd", "validUntil", "checkedAt",
          "schemaVersion"]

def clone(): return json.loads(json.dumps(ACTION))

# N1 — Class A normalisation never applied at all. Insight's vector; strict superset of ours.
a = clone()
for k in HEX_A: a["params"]["oracle_safety_check_v2"][k] = d[k]
for k in ("attester", "signature", "uid"): a["params"]["eip712_attestation"][k] = rec[k]
N1 = negvec("Class A hex carried raw from the receipt: 0x prefix and original casing, all 7 fields",
            "5.2 Class A", a)
ck("N1 reproduces Insight's e11080d7…", N1["action_id_hex"].startswith("e11080d7"))

# N2 — destinationAssetId lowercased and NOTHING else.
a = clone()
s = a["params"]["oracle_safety_check_v2"]
s["destinationAssetId"] = s["destinationAssetId"].lower()
N2 = negvec("Class B destinationAssetId lowercased, nothing else touched (EIP-55 checksum destroyed)",
            "5.2 Class B", a)

# N3 — target lowercased and NOTHING else. Neither side tested this before.
a = clone()
a["target"] = a["target"].lower()
N3 = negvec("Class B target lowercased, nothing else touched (constructed field, previously untested)",
            "5.2 Class B", a)

# N4 — uint256 as JSON numbers. The one case both sides already matched on.
a = clone()
s = a["params"]["oracle_safety_check_v2"]
for k in UINTS: s[k] = int(s[k])
N4 = negvec("uint256 struct fields as JSON numbers instead of decimal strings",
            "5.1 foreign struct", a)
ck("N4 still reproduces the agreed 64d36637…", N4["action_id_hex"].startswith("64d36637"))

# N5 — outcome.schema_version as a decimal string. Pins the corrected 5.1 scope.
a = clone()
a["outcome"]["schema_version"] = str(a["outcome"]["schema_version"])
N5 = negvec("VRT1-native outcome.schema_version as a decimal string instead of an integer",
            "5.1 VRT1-native", a)

# Retained: the round-1 conjunction, so Insight's existing assertion does not go red.
a = clone()
s = a["params"]["oracle_safety_check_v2"]
s["destinationAssetId"] = s["destinationAssetId"].lower()
a["target"] = a["target"].lower()
NCOMBINED = negvec("both Class B fields lowercased (round-1 vector; conjunction of N2 and N3)",
                   "5.2 Class B", a)
ck("retained combined case is the round-1 0182bf4d…",
   NCOMBINED["action_id_hex"].startswith("0182bf4d"))

_aid, _sig = action_id(ACTION), bytes.fromhex(shipped["sig_hex"])
flip = bytearray(_sig); flip[10] ^= 0x01

ids = [N1, N2, N3, N4, N5, NCOMBINED]
ck("every negative differs from the canonical action_id",
   all(x["action_id_hex"] != CANON_ID for x in ids))
ck("every negative is distinct from every other",
   len({x["action_id_hex"] for x in ids}) == len(ids))

w(OUT, "negatives_oracle_safety_check.json", {
    "spec_section": "8",
    "action_type": "insight.oracle-safety-check",
    "canonical_action_id_hex": CANON_ID,
    "how_to_use": "Each case is a literal input. Hash canonical_bytes_hex with "
                  "tagged_hash('VRT1/agent-action', bytes) and confirm you get action_id_hex, "
                  "then confirm your verifier REJECTS it. Do not regenerate the mutation.",
    "one_rule_each": True,
    "cases": [N1, N2, N3, N4, N5],
    "retained_from_round_1": [NCOMBINED],
    "signature_cases": [
        {"case": "one flipped signature byte", "sig_hex": flip.hex(), "verify_expected": False},
        {"case": "valid signature, wrong Merkle leaf",
         "leaf_hex": sha256(b"wrong").hex(), "root_expected_mismatch": True,
         "verify_expected": False}]})

w(OUT, "positive_oracle_safety_check.json", {
    "spec_section": "8", "action_type": "insight.oracle-safety-check",
    "note": "Unchanged from round 1. Restated here so the suite is self-contained.",
    **vec(ACTION)})

# =====================================================================================
# PART 2 — key_registry_snapshot: generic type, synthetic registry, chained pair
# =====================================================================================
CUSTODY = ["hot_process", "kms", "hsm", "offline", "air_gapped", "unknown"]

def synth_addr(seed):                 # deterministic, obviously synthetic, Class A normalised
    return sha256(seed.encode()).hex()[:40]

K_OLD = {"key_id": "signer-2025-08", "key_type": "eth_address",
         "public_key": synth_addr("vrt1-example-signer-2025-08"),
         "custody": "hot_process", "revoked": False,
         "valid_from": 1754006400, "valid_until": 1772592000}
K_MID = {"key_id": "signer-2026-02", "key_type": "eth_address",
         "public_key": synth_addr("vrt1-example-signer-2026-02"),
         "custody": "hot_process", "revoked": False,
         "valid_from": 1770000000, "valid_until": None}
K_NEW = {"key_id": "signer-2026-09", "key_type": "eth_address",
         "public_key": synth_addr("vrt1-example-signer-2026-09"),
         "custody": "hsm", "revoked": False,
         "valid_from": 1788000000, "valid_until": None}

def snapshot_action(keys, ts, parent=None):
    a = {"action_type": "key_registry_snapshot",
         "agent": DEMO_AGENT,
         "outcome": {"active_count": sum(1 for k in keys if not k["revoked"]),
                     "revoked_count": sum(1 for k in keys if k["revoked"])},
         "params": {"snapshot": {"keys": keys, "schema_version": 1, "ts": ts}},
         "target": "example.attester/key-registry",
         "ts": ts,
         "v": 1}
    if parent: a["parent_action"] = parent          # null/absent parent MUST be omitted (8.1)
    return a

# Genesis — newest first, which is the order a registry renders. parent_action ABSENT.
SNAP1 = snapshot_action([K_MID, K_OLD], 1787000000)
V1 = vec(SNAP1, "Genesis snapshot. No parent_action — the field is omitted, never null (8.1).")
ck("genesis snapshot omits parent_action", "parent_action" not in SNAP1)

# Second snapshot — a rotation and a revocation, chained to the first.
K_OLD_REVOKED = dict(K_OLD, revoked=True)
SNAP2 = snapshot_action([K_NEW, K_MID, K_OLD_REVOKED], 1788100000, parent=V1["action_id_hex"])
V2 = vec(SNAP2, "Chained snapshot: one key added under different custody, one revoked. "
                "parent_action is the previous snapshot's action_id.")
ck("chained snapshot carries the genesis action_id as parent",
   SNAP2["parent_action"] == V1["action_id_hex"])
ck("counts partition keys[] on `revoked`",
   SNAP2["outcome"] == {"active_count": 2, "revoked_count": 1})

def rclone(): return json.loads(json.dumps(SNAP1))

# R1 — public_key carried raw, the violation that motivated the rule.
a = rclone()
a["params"]["snapshot"]["keys"][0]["public_key"] = "0x" + \
    "".join(c.upper() if i % 3 == 0 else c
            for i, c in enumerate(a["params"]["snapshot"]["keys"][0]["public_key"]))
R1 = negvec("public_key carried 0x-prefixed and mixed-case", "5.2 Class A", a)

# R2 — snapshot.ts as a decimal string. VRT1-native integers stay integers.
a = rclone(); a["params"]["snapshot"]["ts"] = str(a["params"]["snapshot"]["ts"])
R2 = negvec("VRT1-native snapshot.ts as a decimal string instead of an integer",
            "5.1 VRT1-native", a)

# R3 — open-ended validity expressed by omission instead of null.
a = rclone(); del a["params"]["snapshot"]["keys"][0]["valid_until"]
R3 = negvec("open-ended valid_until omitted instead of serialised as null",
            "key_registry_snapshot: null valid_until MUST be serialised", a)

# R4 — keys[] reordered. Canonical JSON sorts object keys; it never sorts arrays.
a = rclone()
a["params"]["snapshot"]["keys"] = sorted(a["params"]["snapshot"]["keys"],
                                         key=lambda k: k["key_id"])
R4 = negvec("keys[] sorted by key_id instead of preserved in record order",
            "1.4 canonical JSON sorts object keys, never array elements", a)
ck("R4 actually changes the array order",
   [k["key_id"] for k in a["params"]["snapshot"]["keys"]] !=
   [k["key_id"] for k in SNAP1["params"]["snapshot"]["keys"]])

# R5 — counts disagree with keys[]. A semantic rule, not an encoding one.
a = rclone(); a["outcome"]["active_count"] = 3
R5 = negvec("outcome.active_count disagrees with keys[] (2 unrevoked entries, count says 3)",
            "key_registry_snapshot: counts MUST equal the partition of keys[] on `revoked`", a)

REG_NEG = [R1, R2, R3, R4, R5]
ck("every registry negative differs from the genesis action_id",
   all(x["action_id_hex"] != V1["action_id_hex"] for x in REG_NEG))
ck("every registry negative is distinct",
   len({x["action_id_hex"] for x in REG_NEG}) == len(REG_NEG))

REGISTRY_DOC = {
    "spec_section": "8.4",
    "action_type": "key_registry_snapshot",
    "status": "REGISTERED in VRT1 Section 8.5 — generic, not vendor-namespaced",
    "vectors_live_at": "vrt1-spec/test-vectors/key_registry_snapshot.json (generated by that "
                       "repo's tests/generate_vectors.py; the positives below are the same "
                       "design under this suite's demo key)",
    "origin": "Type contributed by Insight (oracleinsight.xyz), who built the first "
              "implementation as insight.key-registry-snapshot. Generalised with their "
              "agreement: every attester that publishes a key registry has the same problem, "
              "so namespacing it would make two identical records non-interoperable.",
    "purpose": "A key registry lives on the operator's own server and its validity windows "
               "are self-asserted. Anchoring the snapshot moves the registry's trust from "
               "the operator's web server to Bitcoin. Chaining the snapshots turns "
               "'each snapshot is authentic' into 'this is the complete history' — without a "
               "chain, an operator can publish snapshot A and snapshot C and silently omit B, "
               "which is exactly how a briefly-active key would be hidden.",
    "schema": {
        "action_type": "MUST be the literal string 'key_registry_snapshot'.",
        "target": "Operator-chosen registry identifier. MUST be stable across the chain.",
        "params.snapshot.keys": "Array of key entries. ORDER IS SIGNIFICANT and MUST be "
                                "preserved; canonical JSON sorts object keys, never arrays.",
        "params.snapshot.schema_version": "Integer. VRT1-native.",
        "params.snapshot.ts": "Integer Unix seconds, as of snapshot construction.",
        "outcome.active_count": "Integer. Count of entries with revoked == false.",
        "outcome.revoked_count": "Integer. Count of entries with revoked == true.",
        "parent_action": "Previous snapshot's action_id. OMITTED for the genesis snapshot "
                         "(8.1: a null parent MUST be omitted, never serialised)."},
    "key_entry": {
        "key_id": "Operator-scoped stable identifier.",
        "key_type": "REQUIRED. What public_key holds, so a consumer can mechanise the "
                    "'did this key sign that receipt' check: 'eth_address' | "
                    "'secp256k1_xonly' | 'secp256k1_compressed' | 'ed25519'. Extensible.",
        "public_key": "Class A hex (5.2): 0x stripped, lowercase.",
        "custody": "REQUIRED. Declared custody of the private key: " + " | ".join(CUSTODY) +
                   ". The enumeration is UNORDERED. VRT1 supplies the vocabulary so custody "
                   "is comparable across attesters; it does not rank the values and does not "
                   "endorse any of them. 'unknown' is always available and is not a failure.",
        "revoked": "Boolean.",
        "valid_from": "Integer Unix seconds.",
        "valid_until": "Integer Unix seconds, or null for open-ended. A null valid_until MUST "
                       "be SERIALISED as null, not omitted — unlike parent_action. Two "
                       "spellings of 'no expiry' would otherwise produce two action_ids."},
    "validity_semantics": "A consumer checks key validity AT SIGNING TIME. A receipt signed "
                          "while its key was inside its published window stays verifiable "
                          "after that window closes; revocation stops forward trust and does "
                          "not reach backward into an anchored set.",
    "note_on_active": "'Active' means 'not revoked'. It does not mean 'currently inside its "
                      "window' — window membership is evaluated by the verifier against a "
                      "signing time, not summarised in the record.",
    "keys_are_synthetic": "The public_key values are sha256-derived placeholders, not real "
                          "key material for any operator.",
    "positives": [V1, V2],
    "negatives": REG_NEG,
    "demo_key": {"privkey_hex_demo_only": DEMO_SECK.hex(), "aux_rand_hex": AUX.hex(),
                 "agent_pubkey_xonly_hex": DEMO_AGENT}}

w(OUT, "key_registry_snapshot_DESIGN.json", REGISTRY_DOC)

# =====================================================================================
# PART 3 — interop vector: Insight's own draft, byte-exact, plus the registration candidate
# =====================================================================================
INSIGHT_SNAP = {
    "keys": [
        {"key_id": "insight-oracle-safety-v2",
         "public_key": norm_hex("0xa268676C85b927D64a4e2384636874f76D69e419"),
         "valid_from": "2026-08-05", "valid_until": "2026-09-02T17:35:36.000Z",
         "revoked": False},
        {"key_id": "insight-oracle-safety-v2-202609",
         "public_key": norm_hex("0x6506F789Edd43338A416f59822A63F309f97E8ce"),
         "valid_from": "2026-08-26T17:35:36.000Z", "valid_until": None, "revoked": False}],
    "schema_version": 1, "ts": 1787804390}

INSIGHT_DRAFT = {"action_type": "key_registry_snapshot", "agent": DEMO_AGENT,
                 "outcome": {"active_count": 2, "revoked_count": 0},
                 "params": {"snapshot": INSIGHT_SNAP},
                 "target": "insight.key-registry", "ts": 1787804390, "v": 1}

DRAFT_TARGET = "29e75d580c843d9aae3ba18d2fdb6ee92c240fa045d518409bfcc8d6d022b2d0"
DRAFT = vec(INSIGHT_DRAFT, "Insight's 2026-08-28 draft, reproduced byte-exact.")
ck("Insight draft reproduces 29e75d58… as they reported", DRAFT["action_id_hex"] == DRAFT_TARGET)
ck("Insight draft is 636 bytes as they reported", DRAFT["canonical_bytes_len"] == 636)

def iso_to_unix(s):
    if len(s) == 10: s += "T00:00:00.000Z"          # <-- the interpretation this pins down
    return calendar.timegm(time.strptime(s.replace(".000Z", "Z"), "%Y-%m-%dT%H:%M:%SZ"))

CAND_SNAP = {
    "keys": [
        dict(k, key_type="eth_address", custody="hot_process",
             valid_from=iso_to_unix(k["valid_from"]),
             valid_until=(iso_to_unix(k["valid_until"]) if k["valid_until"] else None))
        for k in INSIGHT_SNAP["keys"]],
    "schema_version": 1, "ts": 1787804390}
CANDIDATE = {**INSIGHT_DRAFT, "params": {"snapshot": CAND_SNAP}}
CAND = vec(CANDIDATE, "NOT a conformance vector. What the same registry becomes under the "
                      "proposed registration schema: integer timestamps, key_type, custody.")

w(OUT, "interop_insight_key_registry.json", {
    "spec_section": "8.4", "action_type": "key_registry_snapshot",
    "purpose": "Byte-exact interop target for Insight's own draft record, so both "
               "implementations line up before the spec text is finalised.",
    "draft_as_sent": DRAFT,
    "draft_action_id_as_reported_by_insight": DRAFT_TARGET,
    "provenance": "Recomputed from Insight's 2026-08-28 file: 636 canonical bytes, "
                  "action_id 29e75d58..., matching the values they reported.",
    "record_type_note": "Their envelope carries record_type 'key_registry_snapshot:v1' while "
                        "the signed payload carries action_type 'key_registry_snapshot' and "
                        "versions via params.snapshot.schema_version. Two version dials, only "
                        "one inside the signed bytes. schema_version is authoritative; the "
                        "':v1' suffix is file metadata and is neither signed nor anchored.",
    "registration_candidate": CAND,
    "open_questions_the_candidate_answers": [
        "valid_from mixes two formats in one field today ('2026-08-05' and "
        "'2026-08-26T17:35:36.000Z'). Both are legal RFC 3339 and they are not the same "
        "string, so the same instant has two spellings and two action_ids. Integer Unix "
        "seconds removes the class: it is what 8.1 `ts` already uses.",
        "key_type is required so 'was this receipt signed by a key in the registry' is "
        "mechanisable — an Ethereum address is a hash of a public key, not a public key.",
        "custody is required per key, which is where the field both sides agreed on belongs: "
        "custody is a property of a key, not of every receipt, and it becomes anchored and "
        "chained for free."]})

# ---------------- README ----------------
w(OUT, "README.json", {
    "suite": "VRT1 shared conformance vectors, round 2",
    "generated": "2026-08-28",
    "vrt1_version": 1,
    "supersedes": "the negative half of insight-vectors/negative.json",
    "canonical_json": "json.dumps(obj, sort_keys=True, separators=(',',':'), "
                      "ensure_ascii=False) — object keys sorted recursively by UTF-8 "
                      "codepoint, no whitespace, non-ASCII NOT escaped, ARRAYS NEVER SORTED",
    "rule_5_1_integer_encoding":
        "Decimal strings apply to the integer-typed fields of a signed foreign struct carried "
        "inside params. VRT1-native payload integers (v, ts, schema_version, counts) are JSON "
        "integers, always, regardless of value. The test is struct ownership, not magnitude: "
        "a threshold would be a canonicalisation bug, because a value crossing it would change "
        "type mid-life. Decimal strings are base 10, no leading zeros, no leading '+'.",
    "rule_5_2_hex_classes": {
        "class_A_normalise_strip_0x_lowercase":
            "Hex-encoded byte strings, at EVERY depth of the payload: bytes32 digests, "
            "signatures, addresses, key material.",
        "class_B_verbatim_never_touch":
            "CAIP-19 asset identifiers and anything built from them. 0x is part of the "
            "identifier and EIP-55 casing is a checksum.",
        "test": "if lowercasing loses information it is Class B",
        "applies_recursively": True},
    "negatives_are_inputs":
        "Each negative ships as literal canonical bytes and an expected action_id, violating "
        "exactly one rule. Reconstructing a negative from a description tests the "
        "reconstruction, not the rule.",
    "files": {
        "positive_oracle_safety_check.json": "round-1 positive, restated",
        "negatives_oracle_safety_check.json": "five one-rule negatives + round-1 conjunction",
        "key_registry_snapshot_DESIGN.json": "rationale + schema for the generic type "
                                             "(vectors themselves ship in vrt1-spec)",
        "interop_insight_key_registry.json": "Insight's draft byte-exact + registration candidate"},
    "demo_key_warning": "The agent key is 0x55..55, published deliberately so the vectors are "
                        "reproducible. It is never a production key."})

# ---------------- self-verify ----------------
print("\nSelf-verification:")
ck("genesis snapshot signature verifies",
   schnorr_verify(bytes.fromhex(V1["action_id_hex"]), DEMO_PX, bytes.fromhex(V1["sig_hex"])))
ck("chained snapshot signature verifies",
   schnorr_verify(bytes.fromhex(V2["action_id_hex"]), DEMO_PX, bytes.fromhex(V2["sig_hex"])))
ck("Insight draft signature verifies",
   schnorr_verify(bytes.fromhex(DRAFT["action_id_hex"]), DEMO_PX, bytes.fromhex(DRAFT["sig_hex"])))
ck("every literal byte string round-trips to its stated action_id",
   all(tagged_hash("VRT1/agent-action", bytes.fromhex(x["canonical_bytes_hex"])).hex()
       == x["action_id_hex"]
       for x in [N1, N2, N3, N4, N5, NCOMBINED, V1, V2, DRAFT, CAND] + REG_NEG))
ck("no Class A field anywhere retains a 0x prefix in a positive vector",
   not any("0x" in json.dumps(x["action"]) for x in [V1, V2, DRAFT, CAND]))
ck("registration candidate timestamps are all integers",
   all(isinstance(k["valid_from"], int) and
       (k["valid_until"] is None or isinstance(k["valid_until"], int))
       for k in CAND["action"]["params"]["snapshot"]["keys"]))

ok = True
for label, cond in CHECKS:
    ok = ok and cond
    print(f"  [{'PASS' if cond else 'FAIL'}] {label}")
print("\n" + "=" * 74)
print("CONFORMANCE VECTORS:", "ALL SELF-CHECKS PASS" if ok else "*** FAILED ***")
print("=" * 74)
print(f"\n  oracle-safety-check canonical : {CANON_ID}")
print(f"  registry genesis              : {V1['action_id_hex']}")
print(f"  registry chained (#2)         : {V2['action_id_hex']}")
print(f"  Insight draft (interop target): {DRAFT['action_id_hex']}  [{DRAFT['canonical_bytes_len']} bytes]")
print(f"  registration candidate        : {CAND['action_id_hex']}  [{CAND['canonical_bytes_len']} bytes]")
sys.exit(0 if ok else 1)
