import { Blockchain } from '@/types/oracle';

export const DIA_CHAIN_MAPPING: Record<Blockchain, string> = {
  [Blockchain.ETHEREUM]: 'Ethereum',
  [Blockchain.ARBITRUM]: 'Arbitrum',
  [Blockchain.POLYGON]: 'Polygon',
  [Blockchain.AVALANCHE]: 'Avalanche',
  [Blockchain.BNB_CHAIN]: 'BinanceSmartChain',
  [Blockchain.BASE]: 'Base',
  [Blockchain.OPTIMISM]: 'Optimism',
  [Blockchain.FANTOM]: 'Fantom',
  [Blockchain.CRONOS]: 'Cronos',
  [Blockchain.MOONBEAM]: 'Moonbeam',
  [Blockchain.GNOSIS]: 'Gnosis',
  [Blockchain.KAVA]: 'Kava',
  [Blockchain.SOLANA]: 'Solana',
  [Blockchain.SUI]: 'Sui',
  [Blockchain.APTOS]: 'Aptos',
  [Blockchain.INJECTIVE]: 'Injective',
  [Blockchain.SEI]: 'Sei',
  [Blockchain.COSMOS]: 'Cosmos',
  [Blockchain.OSMOSIS]: 'Osmosis',
  [Blockchain.JUNO]: 'Juno',
  [Blockchain.CELESTIA]: 'Celestia',
  [Blockchain.TRON]: 'Tron',
  [Blockchain.TON]: 'Ton',
  [Blockchain.NEAR]: 'Near',
  [Blockchain.AURORA]: 'Aurora',
  [Blockchain.CELO]: 'Celo',
  [Blockchain.STARKNET]: 'Starknet',
  [Blockchain.BLAST]: 'Blast',
  [Blockchain.CARDANO]: 'Cardano',
  [Blockchain.POLKADOT]: 'Polkadot',
  [Blockchain.MANTLE]: 'Mantle',
  [Blockchain.LINEA]: 'Linea',
  [Blockchain.SCROLL]: 'Scroll',
  [Blockchain.ZKSYNC]: 'ZkSync',
  [Blockchain.MOONRIVER]: 'Moonriver',
  [Blockchain.METIS]: 'Metis',
  [Blockchain.STARKEX]: 'StarkEx',
  [Blockchain.STELLAR]: 'Stellar',
  [Blockchain.FLARE]: 'Flare',
};
