import { flareSymbols } from './flareConstants';
import { reflectorSymbols } from './reflectorConstants';
import { supraSymbols } from './supraConstants';
import { twapSymbols } from './twapConstants';

// Note: These symbols have available Chainlink price feeds on at least one chain
const chainlinkSymbols = [
  // Crypto
  'BTC',
  'ETH',
  'LINK',
  'MATIC',
  'AVAX',
  'USDT',
  'USDC',
  'DAI',
  'AAVE',
  'APE',
  'LDO',
  '1INCH',
  'WBTC',
  'STETH',
  'SHIB',
  'UNI',
  'NEAR',
  'APT',
  'ARB',
  'OP',
  'SNX',
  'CRV',
  'SUSHI',
  'GMX',
  'GRT',
  'AXS',
  'INJ',
  'SUI',
  'SEI',
  'TIA',
  'TON',
  'PEPE',
  'WIF',
  'LUSD',
  'MNT',
  'RPL',
  'CVX',
  'CAKE',
  'BONK',
  'MKR',
  'COMP',
  'YFI',
  'FRAX',
  'SOL',
  'DOGE',
  'BNB',
  'XRP',
  'ADA',
  'DOT',
  'LTC',
  'TRX',
  'BCH',
  'ATOM',
  'XLM',
  'ETC',
  'FIL',
  'FLOW',
  'FTM',
  'HBAR',
  'ICP',
  'MANA',
  'SAND',
  'GALA',
  'DYDX',
  'BAL',
  'BAT',
  'BAND',
  'BUSD',
  'DASH',
  'ENJ',
  'IOTX',
  'KNC',
  'LRC',
  'OCEAN',
  'OMG',
  'REN',
  'STORJ',
  'UMA',
  'ZRX',
  'XTZ',
  'ANKR',
  'PAXG',
  'QNT',
  // Forex (verified on Ethereum Mainnet)
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'BRL',
  'CNY',
  'KRW',
  'MXN',
  'SGD',
  'INR',
  'NZD',
  'TRY',
  'ZAR',
  'PHP',
  'IDR',
  // Commodity (verified on Ethereum Mainnet)
  'XAU',
  'XAG',
  // Equities (verified on Ethereum Mainnet)
  'AAPL',
  'AMZN',
  'TSLA',
  'GOOGL',
  'MSFT',
  'META',
  'NVDA',
  'COIN',
] as const;

// RedStone supported symbols (based on actual verification results - 2026-04-14)
// Only including symbols that can be correctly fetched
export const redstoneSymbols = [
  // Major Cryptocurrencies
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'XRP',
  'ADA',
  'DOGE',
  'TRX',
  'DOT',
  'MATIC',
  'LTC',
  'AVAX',
  'LINK',
  'ATOM',
  'UNI',
  'XLM',
  'ETC',
  'BCH',
  'FIL',
  'NEAR',
  'APT',
  'ARB',
  'OP',
  'INJ',
  // DeFi Tokens
  'AAVE',
  'SNX',
  'CRV',
  'COMP',
  'YFI',
  'SUSHI',
  '1INCH',
  'BAL',
  'LDO',
  'FXS',
  'GMX',
  'DYDX',
  'RPL',
  'ENS',
  'GRT',
  'BLUR',
  'APE',
  'SAND',
  'MANA',
  'AXS',
  'GALA',
  'IMX',
  'RNDR',
  'THETA',
  'KAVA',
  'RUNE',
  'CAKE',
  'CVX',
  // LRT (partially available)
  'METH',
  // Yield-Bearing Assets (partially available)
  'EIGEN',
  // Stablecoins
  'USDC',
  'USDT',
  'DAI',
  'FRAX',
  'LUSD',
  'TUSD',
  'USDD',
  // Wrapped Assets
  'WBTC',
  // Layer 2 Tokens (partially available)
  'MNT',
  'ZK',
  'MANTA',
  // Others
  'PEPE',
  'BONK',
  'WIF',
  'FLOKI',
  // Forex (verified via RedStone API)
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'NZD',
  'SGD',
  'HKD',
  'KRW',
  'INR',
  'MXN',
  'BRL',
  'SEK',
  'NOK',
  'TRY',
  'ZAR',
  // Commodity (verified via RedStone API)
  'XAU',
  'XAG',
  'XPT',
  'XPD',
] as const;

// DIA supported symbols (based on actual detection results - 2026-04-14)
// Only including symbols that can be correctly fetched
export const diaSymbols = [
  'BTC',
  'ETH',
  'BNB',
  'SOL',
  'MATIC',
  'LTC',
  'AVAX',
  'LINK',
  'ATOM',
  'UNI',
  'XLM',
  'ETC',
  'BCH',
  'FIL',
  'NEAR',
  'ARB',
  'AAVE',
  'SNX',
  'CRV',
  'MKR',
  'COMP',
  'YFI',
  'SUSHI',
  '1INCH',
  'BAL',
  'LDO',
  'GMX',
  'DYDX',
  'USDC',
  'USDT',
  'DAI',
  'FRAX',
  'BUSD',
  'WBTC',
  'WETH',
  'XRP',
  'DOGE',
  'ADA',
  'DOT',
  'TRX',
  'TON',
  'SHIB',
  'PEPE',
  'WIF',
  'OP',
  'APT',
  'INJ',
  'TIA',
  'SEI',
  'SUI',
  'FET',
  'RNDR',
  'ICP',
  'HBAR',
  'FTM',
  'FLOW',
  'EOS',
  'XTZ',
  'ZEC',
  'XMR',
  'VET',
  'ALGO',
  'EGLD',
  'KSM',
  'QNT',
  'OCEAN',
  'MANA',
  'SAND',
  'GALA',
  'AXS',
  'ENJ',
  'CHZ',
  'CELO',
  'CRO',
  'ZIL',
  'BAT',
  'ZRX',
  'STORJ',
  'ANKR',
  'CELR',
  'HNT',
  'IOTA',
  'IOTX',
  'KNC',
  'LRC',
  'NEO',
  'OMG',
  'ONT',
  'WAVES',
  'XVG',
  'NANO',
  'SC',
  'RVN',
  'DCR',
  'DGB',
  'ICX',
  'LSK',
  'STEEM',
  'WAN',
] as const;

// API3 supported symbols (based on actual detection results - 2026-04-14)
// Only including symbols that can be correctly fetched
const api3Symbols = [
  // Crypto
  'ARB',
  'AVAX',
  'BAL',
  'BNB',
  'BTC',
  'COMP',
  'DAI',
  'ETH',
  'SOL',
  'USDC',
  'USDT',
  'WBTC',
  'AAVE',
  'ADA',
  'ATOM',
  'DOGE',
  'DOT',
  'LINK',
  'LTC',
  'MATIC',
  'MKR',
  'OP',
  'SHIB',
  'SNX',
  'UNI',
  'XRP',
  'YFI',
  'CRV',
  'SUSHI',
  'GRT',
  '1INCH',
  'PEPE',
  'BONK',
  'WIF',
  'INJ',
  'SUI',
  'SEI',
  'TIA',
  'TON',
] as const;

export const API3_AVAILABLE_PAIRS: Record<string, string[]> = {
  ethereum: [
    'BAL',
    'BTC',
    'COMP',
    'ETH',
    'USDC',
    'DAI',
    'LINK',
    'UNI',
    'AAVE',
    'SNX',
    'MKR',
    'YFI',
    'CRV',
    'SUSHI',
    'GRT',
    '1INCH',
    'SHIB',
    'PEPE',
    'BONK',
    'WIF',
  ],
  arbitrum: ['ARB', 'AVAX', 'BTC', 'COMP', 'DAI', 'ETH', 'USDC', 'USDT', 'WBTC'],
  polygon: ['ARB', 'AVAX', 'BNB', 'BTC', 'ETH', 'USDC', 'WBTC', 'MATIC'],
  base: ['BNB', 'BTC', 'DAI', 'ETH', 'SOL', 'USDC', 'USDT', 'WBTC', 'AAVE'],
  optimism: ['ETH', 'USDC', 'WBTC', 'OP'],
  avalanche: ['AVAX', 'ETH', 'USDT'],
  'bnb-chain': ['BNB', 'BTC', 'ETH', 'USDC', 'USDT', 'WBTC'],
};

// Pyth supported symbols (based on official documentation, supporting 400+ price feeds)
// Pyth covers cryptocurrencies, forex, commodities, equities, ETFs
export const pythSymbols = [
  // Crypto
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'XRP',
  'ADA',
  'DOGE',
  'TRX',
  'DOT',
  'MATIC',
  'LTC',
  'AVAX',
  'LINK',
  'ATOM',
  'UNI',
  'XLM',
  'ETC',
  'BCH',
  'FIL',
  'NEAR',
  'APT',
  'ARB',
  'OP',
  'INJ',
  'SUI',
  'SEI',
  'AAVE',
  'SNX',
  'CRV',
  'COMP',
  'YFI',
  'SUSHI',
  '1INCH',
  'BAL',
  'LDO',
  'GMX',
  'DYDX',
  'RPL',
  'ENS',
  'GRT',
  'BLUR',
  'APE',
  'SAND',
  'MANA',
  'AXS',
  'GALA',
  'IMX',
  'THETA',
  'KAVA',
  'RUNE',
  'CAKE',
  'CVX',
  'SHIB',
  'USDC',
  'USDT',
  'DAI',
  'FRAX',
  'LUSD',
  'TUSD',
  'WBTC',
  'WETH',
  'STETH',
  'RETH',
  'CBETH',
  'WSTETH',
  'FRXETH',
  'WEETH',
  'EZETH',
  'PYTH',
  'PEPE',
  'BONK',
  'WIF',
  'MEME',
  'TIA',
  'TON',
  'MNT',
  'BEAM',
  'MSOL',
  'QTUM',
  'LQTY',
  'ZEN',
  'ETHFI',
  'ZRO',
  'C98',
  'AEVO',
  'MAV',
  'NTRN',
  'B3',
  'COINX',
  'SCR',
  'MOBILE',
  'DBR',
  'HASUI',
  'VVV',
  // Forex (verified via Pyth Hermes API - only feeds with actual data)
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'NZD',
  'SGD',
  'HKD',
  'KRW',
  'INR',
  'MXN',
  'BRL',
  'SEK',
  'NOK',
  'TRY',
  'ZAR',
  'PHP',
  'IDR',
  // Commodity - Metals (verified via Pyth Hermes API)
  'XAU',
  'XAG',
  'XPT',
  'XPD',
  // Commodity - Energy (verified via Pyth Hermes API)
  'USOILSPOT',
  'UKOILSPOT',
  // US Equities (verified via Pyth Hermes API)
  'AAPL',
  'AMZN',
  'TSLA',
  'GOOGL',
  'MSFT',
  'META',
  'NVDA',
  'COIN',
  'LMT',
  'PANW',
  'PFE',
  'TMUS',
  'PLD',
  'SCHW',
  'WM',
  'GLW',
  'FDX',
  'WDAY',
  'TROW',
  'PH',
  'VRT',
  'BRO',
  'IFF',
  'EQR',
  'HUM',
  'FLUT',
  // ETFs (verified via Pyth Hermes API)
  'ARKK',
  'SGOV',
  'VEA',
  'DIVB',
  'FBCG',
  'ICSH',
  'IVW',
  'XLE',
] as const;

// Pyth available chain-trading pair mapping
// Pyth provides the same trading pairs on all supported chains (fetched uniformly via Hermes API)
export const PYTH_AVAILABLE_PAIRS: Record<string, string[]> = {
  ethereum: [...pythSymbols],
  arbitrum: [...pythSymbols],
  optimism: [...pythSymbols],
  polygon: [...pythSymbols],
  solana: [...pythSymbols],
  avalanche: [...pythSymbols],
  'bnb-chain': [...pythSymbols],
  aptos: [...pythSymbols],
  sui: [...pythSymbols],
  base: [...pythSymbols],
  scroll: [...pythSymbols],
  zksync: [...pythSymbols],
  linea: [...pythSymbols],
  mantle: [...pythSymbols],
  blast: [...pythSymbols],
};

// WINkLink supported symbols (primarily supports TRON ecosystem, only including trading pairs with real contract addresses)
export const winklinkSymbols = [
  'BTC',
  'ETH',
  'TRX',
  'USDT',
  'USDC',
  'USDD',
  'WIN',
  'BTT',
  'JST',
  'SUN',
  'LTC',
  'NFT',
  'TUSD',
  'USDJ',
  'WBTC',
] as const;

export const WINKLINK_SYMBOL_ALIASES: Record<string, string> = {
  APENFT: 'NFT',
};

export const WINKLINK_AVAILABLE_PAIRS: Record<string, string[]> = {
  tron: [...winklinkSymbols],
};

// Supra supported symbols (based on actual verification results - 2026-04-16)
// Only including symbols that can be correctly fetched
export { supraSymbols };

export const SUPRA_AVAILABLE_PAIRS: Record<string, string[]> = {
  // Chains supported by project RPC (corresponding to ALCHEMY_*_RPC in .env.local)
  ethereum: [...supraSymbols],
  arbitrum: [...supraSymbols],
  optimism: [...supraSymbols],
  polygon: [...supraSymbols],
  base: [...supraSymbols],
  solana: [...supraSymbols],
  'bnb-chain': [...supraSymbols],
  avalanche: [...supraSymbols],
  // Supra-specific L2 chains
  zksync: [...supraSymbols],
  scroll: [...supraSymbols],
  mantle: [...supraSymbols],
  linea: [...supraSymbols],
  // Other Supra-supported chains
  aptos: [...supraSymbols],
  sui: [...supraSymbols],
  blast: [...supraSymbols],
  // Supra L1 chain
  'supra-chain': [...supraSymbols],
};

export const oracleSupportedSymbols = {
  chainlink: chainlinkSymbols,
  redstone: redstoneSymbols,
  dia: diaSymbols,
  api3: api3Symbols,
  pyth: pythSymbols,
  winklink: winklinkSymbols,
  supra: supraSymbols,
  twap: twapSymbols,
  reflector: reflectorSymbols,
  flare: flareSymbols,
} as const;

export function getAllSupportedSymbols(): string[] {
  const allSymbols = new Set<string>();
  Object.values(oracleSupportedSymbols).forEach((symbols) => {
    symbols.forEach((symbol) => allSymbols.add(symbol));
  });
  return Array.from(allSymbols).sort();
}

const FOREX_SYMBOLS = [
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'NZD',
  'SGD',
  'HKD',
  'CNY',
  'KRW',
  'INR',
  'MXN',
  'BRL',
  'SEK',
  'NOK',
  'TRY',
  'ZAR',
  'PHP',
  'IDR',
] as const;

const COMMODITY_SYMBOLS = ['XAU', 'XAG', 'XPT', 'XPD', 'USOILSPOT', 'UKOILSPOT'] as const;

const STABLECOIN_SYMBOLS = ['USDT', 'USDC', 'DAI', 'FRAX', 'LUSD', 'TUSD', 'USDD', 'BUSD'] as const;

const EQUITY_SYMBOLS = [
  'AAPL',
  'AMZN',
  'TSLA',
  'GOOGL',
  'MSFT',
  'META',
  'NVDA',
  'COIN',
  'LMT',
  'PANW',
  'PFE',
  'TMUS',
  'PLD',
  'SCHW',
  'WM',
  'GLW',
  'FDX',
  'WDAY',
  'TROW',
  'PH',
  'VRT',
  'BRO',
  'IFF',
  'EQR',
  'HUM',
  'FLUT',
] as const;

const ETF_SYMBOLS = ['ARKK', 'SGOV', 'VEA', 'DIVB', 'FBCG', 'ICSH', 'IVW', 'XLE'] as const;

export function getAssetClass(
  symbol: string
): 'crypto' | 'forex' | 'commodity' | 'stablecoin' | 'equity' | 'etf' {
  const upper = symbol.toUpperCase();
  if ((FOREX_SYMBOLS as readonly string[]).includes(upper)) return 'forex';
  if ((COMMODITY_SYMBOLS as readonly string[]).includes(upper)) return 'commodity';
  if ((STABLECOIN_SYMBOLS as readonly string[]).includes(upper)) return 'stablecoin';
  if ((EQUITY_SYMBOLS as readonly string[]).includes(upper)) return 'equity';
  if ((ETF_SYMBOLS as readonly string[]).includes(upper)) return 'etf';
  return 'crypto';
}

export const ASSET_CLASS_CATEGORIES = [
  { value: 'crypto', label: 'Crypto' },
  { value: 'stablecoin', label: 'Stablecoin' },
  { value: 'forex', label: 'Forex' },
  { value: 'commodity', label: 'Commodity' },
  { value: 'equity', label: 'Equities' },
  { value: 'etf', label: 'ETFs' },
];
