import { flareSymbols } from './flareConstants';
import { reflectorSymbols } from './reflectorConstants';
import { supraSymbols } from './supraConstants';
import { switchboardSymbols } from './switchboardConstants';
import { twapSymbols } from './twapConstants';

// Note: These symbols have available Chainlink price feeds on at least one chain
const chainlinkSymbols = [
  // Crypto
  'BTC',
  'ETH',
  'LINK',
  'MATIC',
  'AVAX',
  'USDT',
  'USDC',
  'DAI',
  'AAVE',
  'APE',
  'LDO',
  '1INCH',
  'WBTC',
  'CBBTC',
  'TBTC',
  'STETH',
  'SHIB',
  'UNI',
  'NEAR',
  'APT',
  'ARB',
  'OP',
  'SNX',
  'CRV',
  'SUSHI',
  'GMX',
  'GRT',
  'AXS',
  'INJ',
  'SUI',
  'SEI',
  'TIA',
  'TON',
  'PEPE',
  'WIF',
  'LUSD',
  'MNT',
  'RPL',
  'CVX',
  'CAKE',
  'BONK',
  'MKR',
  'COMP',
  'YFI',
  'FRAX',
  'SOL',
  'DOGE',
  'BNB',
  'XRP',
  'ADA',
  'DOT',
  'LTC',
  'TRX',
  'BCH',
  'ATOM',
  'XLM',
  'ETC',
  'FIL',
  'FLOW',
  'FTM',
  'HBAR',
  'ICP',
  'MANA',
  'SAND',
  'GALA',
  'DYDX',
  'BAL',
  'BAT',
  'BAND',
  'BUSD',
  'DASH',
  'ENJ',
  'IOTX',
  'KNC',
  'LRC',
  'OCEAN',
  'OMG',
  'REN',
  'STORJ',
  'UMA',
  'ZRX',
  'XTZ',
  'ANKR',
  'PAXG',
  'QNT',
  // Forex (verified on Ethereum Mainnet)
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'BRL',
  'CNY',
  'KRW',
  'MXN',
  'SGD',
  'INR',
  'NZD',
  'TRY',
  'ZAR',
  'PHP',
  'IDR',
  // Commodity (verified on Ethereum Mainnet)
  'XAU',
  'XAG',
  // Equities (verified on Ethereum Mainnet)
  'AAPL',
  'AMZN',
  'TSLA',
  'GOOGL',
  'MSFT',
  'META',
  'NVDA',
  'COIN',
] as const;

// RedStone supported symbols (based on actual verification results - 2026-04-14)
// Only including symbols that can be correctly fetched
export const redstoneSymbols = [
  // Major Cryptocurrencies
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'XRP',
  'ADA',
  'DOGE',
  'TRX',
  'DOT',
  'MATIC',
  'LTC',
  'AVAX',
  'LINK',
  'ATOM',
  'UNI',
  'XLM',
  'ETC',
  'BCH',
  'FIL',
  'NEAR',
  'APT',
  'ARB',
  'OP',
  'INJ',
  // Added 2026-08-15: confirmed served by RedStone's `redstone-rapid` signed
  // price feed (api.redstone.finance/prices?provider=redstone-rapid) but
  // previously absent from this static gate, so RedStone was excluded from the
  // cross-chain quorum for Raul-collaboration BLOCKed assets. Adding them lets
  // RedStone count as an independent participant on Ethereum.
  // NOTE: ICP and STG were also probed but RedStone's rapid feed returns HTTP 500
  // for them (symbol not in the signed feed), so they are intentionally excluded.
  'TAO',
  'HYPE',
  'MEGA',
  'PYUSD',
  // DeFi Tokens
  'AAVE',
  'SNX',
  'CRV',
  'COMP',
  'YFI',
  'SUSHI',
  '1INCH',
  'BAL',
  'LDO',
  'FXS',
  'GMX',
  'DYDX',
  'RPL',
  'ENS',
  'GRT',
  'BLUR',
  'APE',
  'SAND',
  'MANA',
  'AXS',
  'GALA',
  'IMX',
  'RNDR',
  'THETA',
  'KAVA',
  'RUNE',
  'CAKE',
  'CVX',
  // LRT (partially available)
  'METH',
  // Yield-Bearing Assets (partially available)
  'EIGEN',
  // Stablecoins
  'USDC',
  'USDT',
  'DAI',
  'FRAX',
  'LUSD',
  'TUSD',
  'USDD',
  // Wrapped Assets
  'WBTC',
  // Layer 2 Tokens (partially available)
  'MNT',
  'ZK',
  'MANTA',
  // Others
  'PEPE',
  'BONK',
  'WIF',
  'FLOKI',
  // Forex (verified via RedStone API)
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'NZD',
  'SGD',
  'HKD',
  'KRW',
  'INR',
  'MXN',
  'BRL',
  'SEK',
  'NOK',
  'TRY',
  'ZAR',
  // Commodity (verified via RedStone API)
  'XAU',
  'XAG',
  'XPT',
  'XPD',
] as const;

// DIA supported symbols (based on actual detection results - 2026-04-14)
// Only including symbols that can be correctly fetched
export const diaSymbols = [
  'BTC',
  'ETH',
  'BNB',
  'SOL',
  'MATIC',
  'LTC',
  'AVAX',
  'LINK',
  'ATOM',
  'UNI',
  'XLM',
  'ETC',
  'BCH',
  'FIL',
  'NEAR',
  'ARB',
  'AAVE',
  'SNX',
  'CRV',
  'MKR',
  'COMP',
  'YFI',
  'SUSHI',
  '1INCH',
  'BAL',
  'LDO',
  'GMX',
  'DYDX',
  'USDC',
  'USDT',
  'DAI',
  'FRAX',
  'BUSD',
  'WBTC',
  'WETH',
  'XRP',
  'DOGE',
  'ADA',
  'DOT',
  'TRX',
  'TON',
  'SHIB',
  'PEPE',
  'WIF',
  'OP',
  'APT',
  'INJ',
  'TIA',
  'SEI',
  'SUI',
  'FET',
  'RNDR',
  'ICP',
  'HBAR',
  'FTM',
  'FLOW',
  'EOS',
  'XTZ',
  'ZEC',
  'XMR',
  'VET',
  'ALGO',
  'EGLD',
  'KSM',
  'QNT',
  'OCEAN',
  'MANA',
  'SAND',
  'GALA',
  'AXS',
  'ENJ',
  'CHZ',
  'CELO',
  'CRO',
  'ZIL',
  'BAT',
  'ZRX',
  'STORJ',
  'ANKR',
  'CELR',
  'HNT',
  'IOTA',
  'IOTX',
  'KNC',
  'LRC',
  'NEO',
  'OMG',
  'ONT',
  'WAVES',
  'XVG',
  'NANO',
  'SC',
  'RVN',
  'DCR',
  'DGB',
  'ICX',
  'LSK',
  'STEEM',
  'WAN',
] as const;

// API3 dAPIs require an active paid plan; feeds deactivate when plans expire.
// This mapping was last verified against live Ethereum RPC calls on 2026-07-03.
// Non-Ethereum chains are kept as previously detected but should be re-verified
// periodically because the active feed set changes as plans expire.
export const API3_AVAILABLE_PAIRS: Record<string, string[]> = {
  // Synchronised from production oracle_feeds (is_active=true) on 2026-07-31.
  // The sync-feeds discover cron verifies each dAPI by reading the communal
  // proxy before upserting, so this list should stay in sync with the DB.
  ethereum: [
    'ARB',
    'AVAX',
    'BAL',
    'BTC',
    'COMP',
    'DOT',
    'EIGEN',
    'ETH',
    'FRAX',
    'INJ',
    'KAVA',
    'ONDO',
    'OP',
    'PEPE',
    'SEI',
    'SHIB',
    'USDC',
    'YFI',
  ],
  arbitrum: [
    'AAVE',
    'ARB',
    'AVAX',
    'BAL',
    'BTC',
    'COMP',
    'DAI',
    'DOT',
    'ETH',
    'FRAX',
    'INJ',
    'KAVA',
    'OP',
    'PEPE',
    'SEI',
    'SHIB',
    'USDC',
    'USDT',
    'WBTC',
    'YFI',
    'tBTC',
  ],
  polygon: [
    'ARB',
    'AVAX',
    'BAL',
    'BNB',
    'BTC',
    'DOT',
    'ETH',
    'EURC',
    'FRAX',
    'INJ',
    'KAVA',
    'LDO',
    'OP',
    'PEPE',
    'SEI',
    'SHIB',
    'USDC',
    'WBTC',
    'YFI',
  ],
  avalanche: [
    'ARB',
    'AVAX',
    'BAL',
    'BTC',
    'DOT',
    'ETH',
    'FRAX',
    'INJ',
    'KAVA',
    'OP',
    'PEPE',
    'SEI',
    'SHIB',
    'XRP',
    'YFI',
  ],
  'bnb-chain': [
    'ARB',
    'AVAX',
    'BAL',
    'BNB',
    'BTC',
    'DOT',
    'ETH',
    'FRAX',
    'INJ',
    'KAVA',
    'OP',
    'PEPE',
    'SEI',
    'SHIB',
    'USDC',
    'USDT',
    'WBTC',
    'YFI',
  ],
  base: [
    'ARB',
    'AVAX',
    'BAL',
    'BNB',
    'BTC',
    'DAI',
    'DOT',
    'ETH',
    'FRAX',
    'INJ',
    'KAVA',
    'OP',
    'PAXG',
    'PEPE',
    'SEI',
    'SHIB',
    'SOL',
    'USDC',
    'USDT',
    'VVV',
    'WBTC',
    'YFI',
    'cbBTC',
    'stETH',
  ],
  optimism: [
    'ARB',
    'AVAX',
    'BAL',
    'DOT',
    'ETH',
    'FRAX',
    'INJ',
    'KAVA',
    'OP',
    'PEPE',
    'SEI',
    'SHIB',
    'USDC',
    'WBTC',
    'YFI',
  ],
};

// API3 supported symbols (union of API3_AVAILABLE_PAIRS across all chains).
// Keep this derived from API3_AVAILABLE_PAIRS so the hard-coded fallback never
// claims symbols that are not actually active on any chain.
const api3Symbols = [...new Set(Object.values(API3_AVAILABLE_PAIRS).flat())] as const;

// WINkLink supported symbols (primarily supports TRON ecosystem, only including trading pairs with real contract addresses)
export const winklinkSymbols = [
  'BTC',
  'ETH',
  'TRX',
  'USDT',
  'USDC',
  'USDD',
  'WIN',
  'BTT',
  'JST',
  'SUN',
  'LTC',
  'NFT',
  'TUSD',
  'USDJ',
  'WBTC',
] as const;

export const WINKLINK_SYMBOL_ALIASES: Record<string, string> = {
  APENFT: 'NFT',
};

export const WINKLINK_AVAILABLE_PAIRS: Record<string, string[]> = {
  tron: [...winklinkSymbols],
};

// Supra supported symbols (based on actual verification results - 2026-04-16)
// Only including symbols that can be correctly fetched
export { supraSymbols };

export const SUPRA_AVAILABLE_PAIRS: Record<string, string[]> = {
  // Chains supported by project RPC (corresponding to ALCHEMY_*_RPC in .env.local)
  ethereum: [...supraSymbols],
  arbitrum: [...supraSymbols],
  optimism: [...supraSymbols],
  polygon: [...supraSymbols],
  base: [...supraSymbols],
  solana: [...supraSymbols],
  'bnb-chain': [...supraSymbols],
  avalanche: [...supraSymbols],
  // Supra-specific L2 chains
  zksync: [...supraSymbols],
  scroll: [...supraSymbols],
  mantle: [...supraSymbols],
  linea: [...supraSymbols],
  // Other Supra-supported chains
  aptos: [...supraSymbols],
  sui: [...supraSymbols],
  blast: [...supraSymbols],
  // Supra L1 chain
  'supra-chain': [...supraSymbols],
};

// Switchboard Surge feeds are chain-agnostic (served via Crossbar from the
// Solana oracle network), so the same symbol set is available on every chain.
export const SWITCHBOARD_AVAILABLE_PAIRS: Record<string, string[]> = {
  ethereum: [...switchboardSymbols],
  arbitrum: [...switchboardSymbols],
  optimism: [...switchboardSymbols],
  polygon: [...switchboardSymbols],
  solana: [...switchboardSymbols],
  avalanche: [...switchboardSymbols],
  'bnb-chain': [...switchboardSymbols],
  base: [...switchboardSymbols],
  scroll: [...switchboardSymbols],
  zksync: [...switchboardSymbols],
  aptos: [...switchboardSymbols],
  sui: [...switchboardSymbols],
  mantle: [...switchboardSymbols],
  linea: [...switchboardSymbols],
  flare: [...switchboardSymbols],
  'supra-chain': [...switchboardSymbols],
};

export const oracleSupportedSymbols = {
  chainlink: chainlinkSymbols,
  redstone: redstoneSymbols,
  dia: diaSymbols,
  api3: api3Symbols,
  winklink: winklinkSymbols,
  supra: supraSymbols,
  twap: twapSymbols,
  reflector: reflectorSymbols,
  flare: flareSymbols,
  switchboard: switchboardSymbols,
} as const;

export function getAllSupportedSymbols(): string[] {
  const allSymbols = new Set<string>();
  Object.values(oracleSupportedSymbols).forEach((symbols) => {
    symbols.forEach((symbol) => allSymbols.add(symbol));
  });
  return Array.from(allSymbols).sort();
}

const FOREX_SYMBOLS = [
  'EUR',
  'GBP',
  'JPY',
  'CHF',
  'AUD',
  'CAD',
  'NZD',
  'SGD',
  'HKD',
  'CNY',
  'KRW',
  'INR',
  'MXN',
  'BRL',
  'SEK',
  'NOK',
  'TRY',
  'ZAR',
  'PHP',
  'IDR',
] as const;

const COMMODITY_SYMBOLS = ['XAU', 'XAG', 'XPT', 'XPD', 'USOILSPOT', 'UKOILSPOT'] as const;

const STABLECOIN_SYMBOLS = ['USDT', 'USDC', 'DAI', 'FRAX', 'LUSD', 'TUSD', 'USDD', 'BUSD'] as const;

const EQUITY_SYMBOLS = [
  'AAPL',
  'AMZN',
  'TSLA',
  'GOOGL',
  'MSFT',
  'META',
  'NVDA',
  'COIN',
  'LMT',
  'PANW',
  'PFE',
  'TMUS',
  'PLD',
  'SCHW',
  'WM',
  'GLW',
  'FDX',
  'WDAY',
  'TROW',
  'PH',
  'VRT',
  'BRO',
  'IFF',
  'EQR',
  'HUM',
  'FLUT',
] as const;

const ETF_SYMBOLS = ['ARKK', 'SGOV', 'VEA', 'DIVB', 'FBCG', 'ICSH', 'IVW', 'XLE'] as const;

export function getAssetClass(
  symbol: string
): 'crypto' | 'forex' | 'commodity' | 'stablecoin' | 'equity' | 'etf' {
  const upper = symbol.toUpperCase();
  if ((FOREX_SYMBOLS as readonly string[]).includes(upper)) return 'forex';
  if ((COMMODITY_SYMBOLS as readonly string[]).includes(upper)) return 'commodity';
  if ((STABLECOIN_SYMBOLS as readonly string[]).includes(upper)) return 'stablecoin';
  if ((EQUITY_SYMBOLS as readonly string[]).includes(upper)) return 'equity';
  if ((ETF_SYMBOLS as readonly string[]).includes(upper)) return 'etf';
  return 'crypto';
}

export const ASSET_CLASS_CATEGORIES = [
  { value: 'crypto', label: 'Crypto' },
  { value: 'stablecoin', label: 'Stablecoin' },
  { value: 'forex', label: 'Forex' },
  { value: 'commodity', label: 'Commodity' },
  { value: 'equity', label: 'Equities' },
  { value: 'etf', label: 'ETFs' },
];
