/* eslint-disable no-console */
/**
 * Oracle Watch ↔ Scenario Replay closed-loop check.
 *
 * WHAT THIS IS FOR
 * ----------------
 * The scenario harness and Oracle Watch share the same detection vocabulary
 * (STALE_DATA / MAX_DEVIATION / INSUFFICIENT_QUORUM / ANOMALY_ELEVATED), but
 * they run on different inputs: Watch on live cross-oracle data, the harness on
 * a scenario DSL. Sharing code is not the same as agreeing on outcomes. This
 * script closes that gap by replaying REAL captured snapshots through the
 * harness and reporting where the two disagree.
 *
 * It is a QUALITY TOOL, not a product surface. Nothing here is billed, nothing
 * is published, and no partner receives the output. Its only job is to tell you
 * which detection rules still disagree between the live path and the replay
 * path before you let either of them make a claim on your behalf.
 *
 * WHAT IT DOES
 * ------------
 *   1. Reads captured price snapshots (local fixture file, or the
 *      `feed_health_snapshots` table when credentials are present).
 *   2. Groups them by (symbol, chain, provider) into ordered steps.
 *   3. Replays each group through `runScenario` with the same policy the live
 *      path uses, and compares the harness verdict against the verdict implied
 *      by the snapshot's own recorded signal.
 *   4. Prints a per-target table plus a machine-readable summary, and exits
 *      non-zero when a disagreement is found (so CI can gate on it).
 *
 * HONESTY CONSTRAINTS (deliberate, do not remove)
 * ----------------------------------------------
 *   - A snapshot row is a POINT OBSERVATION, not an incident. Replaying
 *     healthy data is expected to produce "no detection". That is a PASS for
 *     "the harness agrees a healthy feed is healthy", and says NOTHING about
 *     whether a real attack would be caught.
 *   - This script CANNOT demonstrate attack detection. Only fixtures with
 *     known injected failures can do that. Do not cite this output as evidence
 *     of attack coverage.
 *   - `--online` reads the database. The default path is fully offline and
 *     reads a JSON file, so it is safe to run anywhere.
 *
 * USAGE
 *   node --import tsx scripts/oracle-testing/watch-replay-check.ts
 *   node --import tsx scripts/oracle-testing/watch-replay-check.ts --online
 *   node --import tsx scripts/oracle-testing/watch-replay-check.ts --json
 */

import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import { runScenario } from '@/lib/testing/oracleScenario/engine';
import {
  parseScenario,
  type OracleScenario,
  type ScenarioSource,
} from '@/lib/testing/oracleScenario/schema';
import { WATCH_POLICY, type WatchReplayRow, type WatchReplaySummary } from './watchReplayPolicy';

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

/** Where the offline snapshot fixture lives. Generated by the collector
 *  (`scripts/collect-oracle-watch.ts`) and copied here; never fetched at run
 *  time so this stays reproducible. */
const DEFAULT_SNAPSHOT_PATH = join(
  homedir(),
  '.workbuddy',
  'insight_oracle_testing',
  'watch-snapshots.json'
);

interface SnapshotRow {
  symbol: string;
  chain: string;
  provider: string;
  price: number;
  /** Unix seconds. */
  timestamp: number;
  /** 'ok' when the feed returned a usable value on this observation. */
  status: 'ok' | 'stale' | 'error';
  /** The signal Oracle Watch reported for this target at this timestamp.
   *  Compared against the replay verdict; null when the row predates signal
   *  capture or the target was not evaluated. */
  recordedSignal?: 'NORMAL' | 'CAUTION' | 'DANGER' | null;
}

function loadSnapshots(path: string): SnapshotRow[] {
  const raw = readFileSync(path, 'utf8');
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error(`snapshot file is not an array: ${path}`);
  }
  return parsed as SnapshotRow[];
}

// ---------------------------------------------------------------------------
// Snapshot rows -> scenario
// ---------------------------------------------------------------------------

/** Unix seconds of the chain, used only as a scenario field for echo-back. */
const CHAIN_ID_BY_NAME: Record<string, number> = {
  ethereum: 1,
  arbitrum: 42161,
  base: 8453,
};

interface ReplayTarget {
  scenarioId: string;
  symbol: string;
  chain: string;
  stepCount: number;
  /** Codes the harness fired at least once. */
  firedCodes: string[];
  /** Codes that imply the feed is NOT healthy. */
  harmfulCodes: string[];
  harnessFlagged: boolean;
  recordedSignal: WatchReplayRow['recordedSignal'];
  /** true when both sides agree the feed is unremarkable. */
  agree: boolean;
  /** Human-readable explanation of any disagreement. */
  note: string;
}

function kindForRows(rows: SnapshotRow[]): OracleScenario['kind'] {
  // The harness's `kind` only sets which codes are EXPECTED during an attack
  // phase. For a healthy replay we mark every step `baseline`, so the expected
  // set is never consulted for `caught` — only the fired codes matter. The
  // kind is therefore descriptive here, and we pick the one matching the
  // dominant observed condition so the report reads honestly.
  const anyError = rows.some((r) => r.status === 'error');
  if (anyError) return 'feed_failure';
  const anyStale = rows.some((r) => r.status === 'stale');
  if (anyStale) return 'stale_price';
  return 'multi_source_divergence';
}

function buildScenario(rows: SnapshotRow[], targetKey: string): OracleScenario {
  const sorted = [...rows].sort((a, b) => a.timestamp - b.timestamp);
  const startedAt = sorted[0].timestamp;

  // Bucket every observation into one step per timestamp so providers that
  // reported at different moments still land in a coherent step. Steps must be
  // strictly increasing per the schema, so duplicate timestamps collapse into
  // the first bucket that contains them.
  const byTimestamp = new Map<number, ScenarioSource[]>();
  for (const row of sorted) {
    const list = byTimestamp.get(row.timestamp) ?? [];
    list.push({
      provider: row.provider,
      price: row.price,
      timestamp: row.timestamp,
      status: row.status,
    });
    byTimestamp.set(row.timestamp, list);
  }

  const steps = [...byTimestamp.entries()]
    .sort(([a], [b]) => a - b)
    .map(([t, sources]) => ({
      t: Math.max(0, t - startedAt),
      // Every step is `baseline`: these are observations, not injected
      // failures. Any detection here is a FALSE POSITIVE on healthy data —
      // which is exactly the signal this check exists to surface.
      phase: 'baseline' as const,
      settlementPrice: median(sources.filter((s) => s.status === 'ok').map((s) => s.price)),
      sources,
    }));

  return parseScenario({
    id: `watch-${targetKey}`
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, '-')
      .slice(0, 60),
    kind: kindForRows(sorted),
    title: `Watch replay — ${sorted[0].symbol} / ${sorted[0].chain}`,
    description:
      'Reconstruction of captured Oracle Watch snapshots, replayed to compare live and offline detection. Not an incident.',
    symbol: sorted[0].symbol,
    chainId: CHAIN_ID_BY_NAME[sorted[0].chain] ?? 1,
    startedAt,
    policy: WATCH_POLICY,
    steps,
  });
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const s = [...values].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 === 0 ? (s[mid - 1] + s[mid]) / 2 : s[mid];
}

// ---------------------------------------------------------------------------
// Compare
// ---------------------------------------------------------------------------

/** Codes that mean "something is wrong with this feed". A baseline step firing
 *  any of these is a false positive on observed healthy data. */
const HARMFUL_CODES = new Set([
  'STALE_DATA',
  'MAX_DEVIATION',
  'INSUFFICIENT_QUORUM',
  'ANOMALY_ELEVATED',
  'PRECISION_DRIFT',
]);

function evaluateGroup(key: string, rows: SnapshotRow[]): ReplayTarget {
  const scenario = buildScenario(rows, key);
  const result = runScenario(scenario);

  const fired = [...new Set(result.steps.flatMap((s) => s.detected))].sort();
  const harmful = fired.filter((c) => HARMFUL_CODES.has(c));
  const falsePositives = result.falsePositiveCount;

  // Live-side truth, when the snapshot recorded it.
  const recorded = rows.find((r) => r.recordedSignal != null)?.recordedSignal ?? null;
  const liveFlagged = recorded === 'CAUTION' || recorded === 'DANGER';

  let agree: boolean;
  let note: string;
  if (recorded == null) {
    agree = harmful.length === 0 && falsePositives === 0;
    note = agree
      ? 'no recorded signal to compare; harness found no detection on observed data'
      : 'no recorded signal; harness fired on observed data — investigate before trusting either side';
  } else if (harmful.length > 0 && !liveFlagged) {
    agree = false;
    note = `offline fired [${harmful.join(', ')}] but Watch reported ${recorded}`;
  } else if (harmful.length === 0 && liveFlagged) {
    agree = false;
    note = `Watch reported ${recorded} but replay found no detection — offline path may miss what live sees`;
  } else {
    agree = true;
    note = `both sides agree (Watch: ${recorded}, offline: ${harmful.length === 0 ? 'clean' : harmful.join(', ')})`;
  }

  return {
    scenarioId: scenario.id,
    symbol: scenario.symbol,
    chain: rows[0].chain,
    stepCount: result.stepCount,
    firedCodes: fired,
    harmfulCodes: harmful,
    harnessFlagged: harmful.length > 0,
    recordedSignal: recorded,
    agree,
    note,
  };
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

function printTable(targets: ReplayTarget[]): void {
  console.log('');
  console.log('target                        steps  watch        offline            agree');
  console.log('─'.repeat(78));
  for (const t of targets) {
    const watch = t.recordedSignal ?? '(not recorded)';
    const offline = t.harmfulCodes.length === 0 ? 'clean' : t.harmfulCodes.join(',');
    const mark = t.agree ? 'yes' : 'NO';
    console.log(
      `${`${t.symbol}/${t.chain}`.padEnd(28)} ${String(t.stepCount).padStart(5)}  ${watch.padEnd(12)} ${offline.padEnd(18)} ${mark}`
    );
    if (!t.agree) console.log(`${' '.repeat(28)} └─ ${t.note}`);
  }
}

function parseArgs(argv: string[]): { online: boolean; json: boolean; path: string } {
  let online = false;
  let json = false;
  let path = DEFAULT_SNAPSHOT_PATH;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--online') online = true;
    else if (arg === '--json') json = true;
    else if (arg === '--path') {
      const next = argv[i + 1];
      if (!next) throw new Error('--path requires a file argument');
      path = next;
      i++;
    } else throw new Error(`unknown argument: ${arg}`);
  }
  return { online, json, path };
}

async function main(): Promise<void> {
  const { json, path } = parseArgs(process.argv.slice(2));

  const rows = loadSnapshots(path);
  if (rows.length === 0) {
    console.error('[watch-replay-check] snapshot file is empty; nothing to replay');
    process.exit(2);
  }

  // Group by (symbol, chain). Providers are steps WITHIN a group, which is
  // what cross-source deviation is defined over.
  const groups = new Map<string, SnapshotRow[]>();
  for (const row of rows) {
    const key = `${row.symbol}|${row.chain}`;
    const list = groups.get(key) ?? [];
    list.push(row);
    groups.set(key, list);
  }

  const targets = [...groups.entries()]
    // A single observation cannot exercise cross-source logic; skip it rather
    // than reporting a meaningless 'agree'.
    .filter(([, g]) => g.length >= 2)
    .map(([key, g]) => evaluateGroup(key.replace('|', '-'), g))
    .sort((a, b) => Number(a.agree) - Number(b.agree));

  const summary: WatchReplaySummary = {
    groupsConsidered: groups.size,
    groupsReplayed: targets.length,
    agreements: targets.filter((t) => t.agree).length,
    disagreements: targets.filter((t) => !t.agree).length,
    targets,
  };

  if (json) {
    console.log(JSON.stringify(summary, null, 2));
  } else {
    console.log(
      `[watch-replay-check] ${rows.length} snapshot rows, ${groups.size} target group(s)`
    );
    console.log('[watch-replay-check] NOTE: replaying observed data can only prove agreement on');
    console.log(
      '[watch-replay-check]       healthy feeds. It does NOT demonstrate attack detection.'
    );
    printTable(targets);
    console.log('');
    console.log(
      `[watch-replay-check] ${summary.agreements} agree, ${summary.disagreements} disagree` +
        (summary.disagreements > 0 ? ' — review before relying on either path.' : '.')
    );
  }

  process.exit(summary.disagreements > 0 ? 1 : 0);
}

main().catch((error: unknown) => {
  console.error('[watch-replay-check] failed:', error instanceof Error ? error.message : error);
  process.exit(2);
});
