'use client';

import { useState } from 'react';

import {
  Search,
  Info,
  Code,
  Clock,
  ChevronRight,
  Hash,
  FileJson,
  AlertCircle,
  CheckCircle,
} from 'lucide-react';

import { useTranslations } from '@/i18n';
import {
  decodeQueryData,
  isValidQueryData,
  POPULAR_QUERIES,
  QUERY_TYPES_INFO,
  formatTimeAgo,
  type DecodedQueryData,
} from '@/lib/oracles/tellorQueryUtils';

import { type TellorQueryDataViewProps } from '../types';

export function TellorQueryDataView({ isLoading }: TellorQueryDataViewProps) {
  const t = useTranslations();
  const [queryInput, setQueryInput] = useState('');
  const [decodedResult, setDecodedResult] = useState<DecodedQueryData | null>(null);
  const [decodeError, setDecodeError] = useState<string | null>(null);

  const handleDecode = () => {
    if (!queryInput.trim()) {
      setDecodeError(t('tellor.queryData.inputRequired') || 'Please enter query data');
      setDecodedResult(null);
      return;
    }

    const input = queryInput.trim();
    if (!isValidQueryData(input)) {
      setDecodeError(t('tellor.queryData.invalidFormat') || 'Invalid query data format');
      setDecodedResult(null);
      return;
    }

    try {
      const result = decodeQueryData(input);
      setDecodedResult(result);
      setDecodeError(null);
    } catch (error) {
      setDecodeError(
        error instanceof Error
          ? error.message
          : t('tellor.queryData.decodeFailed') || 'Failed to decode'
      );
      setDecodedResult(null);
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <div className="flex items-center gap-2 mb-4">
          <Info className="w-4 h-4 text-gray-500" />
          <h3 className="text-base font-medium text-gray-900">
            {t('tellor.queryData.whatIsQueryId') || 'What is Query ID?'}
          </h3>
        </div>
        <div className="bg-gray-50 rounded-lg p-4 space-y-3">
          <p className="text-sm text-gray-600">
            {t('tellor.queryData.queryIdDescription') ||
              'Query ID is a unique identifier for each data request in the Tellor network. It is generated by hashing the query data using keccak256.'}
          </p>
          <div className="flex items-start gap-3 mt-3">
            <Hash className="w-4 h-4 text-cyan-500 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-gray-900">
                {t('tellor.queryData.encodingFormat') || 'Encoding Format'}
              </p>
              <p className="text-xs text-gray-500 mt-1 font-mono">queryId = keccak256(queryData)</p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <FileJson className="w-4 h-4 text-cyan-500 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-gray-900">
                {t('tellor.queryData.queryDataStructure') || 'Query Data Structure'}
              </p>
              <p className="text-xs text-gray-500 mt-1 font-mono">
                queryData = abi.encode(queryType, abi.encode(...params))
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="border-t border-gray-200" />

      <div>
        <div className="flex items-center gap-2 mb-4">
          <Code className="w-4 h-4 text-gray-500" />
          <h3 className="text-base font-medium text-gray-900">
            {t('tellor.queryData.supportedTypes') || 'Supported Query Types'}
          </h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {QUERY_TYPES_INFO.map((type) => (
            <div
              key={type.type}
              className="border border-gray-200 rounded-lg p-4 hover:border-cyan-300 transition-colors"
            >
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-gray-900">{type.name}</span>
                <span className="text-xs px-2 py-0.5 bg-cyan-100 text-cyan-700 rounded">
                  {type.type}
                </span>
              </div>
              <p className="text-xs text-gray-500 mb-3">{type.description}</p>
              <div className="space-y-1">
                <p className="text-xs text-gray-400">
                  {t('tellor.queryData.example') || 'Example'}:
                </p>
                <p className="text-xs font-mono text-gray-600 bg-gray-50 px-2 py-1 rounded">
                  {type.example}
                </p>
              </div>
              <div className="mt-3 pt-3 border-t border-gray-100">
                <p className="text-xs text-gray-400 mb-1">
                  {t('tellor.queryData.parameters') || 'Parameters'}:
                </p>
                <div className="flex flex-wrap gap-1">
                  {type.params.map((param, idx) => (
                    <span
                      key={idx}
                      className="text-xs px-1.5 py-0.5 bg-gray-100 text-gray-600 rounded"
                    >
                      {param}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="border-t border-gray-200" />

      <div>
        <div className="flex items-center gap-2 mb-4">
          <Search className="w-4 h-4 text-gray-500" />
          <h3 className="text-base font-medium text-gray-900">
            {t('tellor.queryData.queryTool') || 'Query ID Decoder'}
          </h3>
        </div>
        <div className="space-y-4">
          <div>
            <label className="block text-sm text-gray-600 mb-2">
              {t('tellor.queryData.enterQueryData') || 'Enter Query Data'}
            </label>
            <div className="flex gap-3">
              <input
                type="text"
                value={queryInput}
                onChange={(e) => setQueryInput(e.target.value)}
                placeholder="0x..."
                className="flex-1 px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-mono focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
              />
              <button
                onClick={handleDecode}
                className="px-6 py-2.5 bg-cyan-500 text-white text-sm font-medium rounded-lg hover:bg-cyan-600 transition-colors"
              >
                {t('tellor.queryData.decode') || 'Decode'}
              </button>
            </div>
          </div>

          {decodeError && (
            <div className="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded-lg">
              <AlertCircle className="w-4 h-4 text-red-500" />
              <span className="text-sm text-red-600">{decodeError}</span>
            </div>
          )}

          {decodedResult && (
            <div className="bg-gray-50 rounded-lg p-4 space-y-4">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                <span className="text-sm font-medium text-gray-900">
                  {t('tellor.queryData.decodedResult') || 'Decoded Result'}
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-gray-400 mb-1">
                    {t('tellor.queryData.queryType') || 'Query Type'}
                  </p>
                  <p className="text-sm font-medium text-gray-900">{decodedResult.queryType}</p>
                </div>
                <div>
                  <p className="text-xs text-gray-400 mb-1">
                    {t('tellor.queryData.queryId') || 'Query ID'}
                  </p>
                  <p className="text-sm font-mono text-gray-900 truncate">
                    {decodedResult.queryId}
                  </p>
                </div>
              </div>

              <div>
                <p className="text-xs text-gray-400 mb-1">
                  {t('tellor.queryData.humanReadable') || 'Human Readable'}
                </p>
                <p className="text-sm font-medium text-cyan-600">{decodedResult.humanReadable}</p>
              </div>

              <div>
                <p className="text-xs text-gray-400 mb-2">
                  {t('tellor.queryData.parameters') || 'Parameters'}
                </p>
                <div className="bg-white border border-gray-200 rounded-lg p-3">
                  <pre className="text-xs font-mono text-gray-700 overflow-x-auto">
                    {JSON.stringify(decodedResult.params, null, 2)}
                  </pre>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="border-t border-gray-200" />

      <div>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Clock className="w-4 h-4 text-gray-500" />
            <h3 className="text-base font-medium text-gray-900">
              {t('tellor.queryData.popularQueries') || 'Popular Queries'}
            </h3>
          </div>
          <span className="text-xs text-gray-400">
            {t('tellor.queryData.topUsed') || 'Most used queries'}
          </span>
        </div>
        <div className="space-y-2">
          {POPULAR_QUERIES.map((query, index) => (
            <div
              key={query.queryId}
              className="flex items-center justify-between py-3 px-4 border border-gray-100 rounded-lg hover:bg-gray-50 transition-colors cursor-pointer group"
              onClick={() => {
                setQueryInput(query.queryData);
                setDecodedResult(null);
                setDecodeError(null);
              }}
            >
              <div className="flex items-center gap-4">
                <span className="text-xs text-gray-400 w-6">{index + 1}</span>
                <div>
                  <p className="text-sm font-medium text-gray-900">{query.description}</p>
                  <p className="text-xs text-gray-400 font-mono mt-0.5">
                    {query.queryId.slice(0, 20)}...
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-6">
                <div className="text-right">
                  <p className="text-xs text-gray-400">
                    {t('tellor.queryData.currentValue') || 'Current Value'}
                  </p>
                  <p className="text-sm font-semibold text-gray-900">{query.currentValue}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-gray-400">
                    {t('tellor.queryData.lastUpdated') || 'Last Updated'}
                  </p>
                  <p className="text-sm text-gray-600">{formatTimeAgo(query.lastUpdated)}</p>
                </div>
                <ChevronRight className="w-4 h-4 text-gray-300 group-hover:text-cyan-500 transition-colors" />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
