import { SupraClient } from '@/lib/oracles';
import { OracleProvider, Blockchain } from '@/types/oracle';

import { COMMON_TABS, createOracleConfig } from './helpers';

export const supraConfig = createOracleConfig({
  provider: OracleProvider.SUPRA,
  name: 'Supra',
  symbol: 'SUPRA',
  defaultChain: Blockchain.ETHEREUM,
  supportedChains: [
    Blockchain.ETHEREUM,
    Blockchain.ARBITRUM,
    Blockchain.OPTIMISM,
    Blockchain.POLYGON,
    Blockchain.AVALANCHE,
    Blockchain.BASE,
    Blockchain.BNB_CHAIN,
    Blockchain.FANTOM,
    Blockchain.SCROLL,
    Blockchain.ZKSYNC,
    Blockchain.MANTLE,
    Blockchain.LINEA,
    Blockchain.SOLANA,
    Blockchain.APTOS,
    Blockchain.SUI,
    Blockchain.INJECTIVE,
    Blockchain.SEI,
    Blockchain.CELO,
    Blockchain.GNOSIS,
    Blockchain.CRONOS,
    Blockchain.MOONBEAM,
    Blockchain.KAVA,
    Blockchain.METIS,
    Blockchain.BLAST,
    Blockchain.STARKNET,
  ],
  clientClass: SupraClient,
  color: '#14B8A6',
  features: {
    hasValidatorAnalytics: true,
    hasPriceFeeds: true,
    hasQuantifiableSecurity: true,
    hasCoreFeatures: true,
    hasDataStreams: true,
    hasCrossChain: true,
    hasRiskAssessment: true,
  },
  tabs: [
    COMMON_TABS.MARKET,
    COMMON_TABS.NETWORK,
    COMMON_TABS.PRICE_FEEDS,
    COMMON_TABS.DATA_STREAMS,
    COMMON_TABS.CROSS_CHAIN,
    COMMON_TABS.ECOSYSTEM,
    COMMON_TABS.RISK,
  ],
  views: [
    {
      id: 'market',
      label: 'Market Data',
      component: 'SupraMarketView',
      default: true,
    },
    { id: 'network', label: 'Network Health', component: 'SupraNetworkView' },
    { id: 'price-feeds', label: 'Price Feeds', component: 'SupraPriceFeedsView' },
    { id: 'cross-chain', label: 'Cross-Chain', component: 'SupraCrossChainView' },
    { id: 'ecosystem', label: 'Ecosystem', component: 'SupraEcosystemView' },
    { id: 'risk', label: 'Risk Assessment', component: 'SupraRiskView' },
  ],
});
