export const enum OracleProvider {
  CHAINLINK = 'chainlink',
  BAND_PROTOCOL = 'band-protocol',
  UMA = 'uma',
  PYTH = 'pyth',
  API3 = 'api3',
  REDSTONE = 'redstone',
  DIA = 'dia',
  WINKLINK = 'winklink',
}

export const enum Blockchain {
  ETHEREUM = 'ethereum',
  ARBITRUM = 'arbitrum',
  OPTIMISM = 'optimism',
  POLYGON = 'polygon',
  SOLANA = 'solana',
  AVALANCHE = 'avalanche',
  FANTOM = 'fantom',
  CRONOS = 'cronos',
  JUNO = 'juno',
  COSMOS = 'cosmos',
  OSMOSIS = 'osmosis',
  BNB_CHAIN = 'bnb-chain',
  BASE = 'base',
  SCROLL = 'scroll',
  ZKSYNC = 'zksync',
  APTOS = 'aptos',
  SUI = 'sui',
  GNOSIS = 'gnosis',
  MANTLE = 'mantle',
  LINEA = 'linea',
  CELESTIA = 'celestia',
  INJECTIVE = 'injective',
  SEI = 'sei',
  TRON = 'tron',
  TON = 'ton',
  NEAR = 'near',
  AURORA = 'aurora',
  CELO = 'celo',
  STARKNET = 'starknet',
  BLAST = 'blast',
  CARDANO = 'cardano',
  POLKADOT = 'polkadot',
  KAVA = 'kava',
  MOONBEAM = 'moonbeam',
  MOONRIVER = 'moonriver',
  METIS = 'metis',
  STARKEX = 'starkex',
}

export const BINANCE = Blockchain.BNB_CHAIN;

export const ORACLE_PROVIDER_VALUES: readonly OracleProvider[] = [
  OracleProvider.CHAINLINK,
  OracleProvider.BAND_PROTOCOL,
  OracleProvider.UMA,
  OracleProvider.PYTH,
  OracleProvider.API3,
  OracleProvider.REDSTONE,
  OracleProvider.DIA,
  OracleProvider.WINKLINK,
] as const;

export const BLOCKCHAIN_VALUES: readonly Blockchain[] = [
  Blockchain.ETHEREUM,
  Blockchain.ARBITRUM,
  Blockchain.OPTIMISM,
  Blockchain.POLYGON,
  Blockchain.SOLANA,
  Blockchain.AVALANCHE,
  Blockchain.FANTOM,
  Blockchain.CRONOS,
  Blockchain.JUNO,
  Blockchain.COSMOS,
  Blockchain.OSMOSIS,
  Blockchain.BNB_CHAIN,
  Blockchain.BASE,
  Blockchain.SCROLL,
  Blockchain.ZKSYNC,
  Blockchain.APTOS,
  Blockchain.SUI,
  Blockchain.GNOSIS,
  Blockchain.MANTLE,
  Blockchain.LINEA,
  Blockchain.CELESTIA,
  Blockchain.INJECTIVE,
  Blockchain.SEI,
  Blockchain.TRON,
  Blockchain.TON,
  Blockchain.NEAR,
  Blockchain.AURORA,
  Blockchain.CELO,
  Blockchain.STARKNET,
  Blockchain.BLAST,
  Blockchain.CARDANO,
  Blockchain.POLKADOT,
  Blockchain.KAVA,
  Blockchain.MOONBEAM,
  Blockchain.MOONRIVER,
  Blockchain.METIS,
  Blockchain.STARKEX,
] as const;
